### PR TITLE
Add Promo image for Friendlyrb in the navbar.

### PR DESCRIPTION
**Pull request by pratiktamang**
This PR adds:

1. Promo image to assets/communities folder.
2. Adds a link to the existing nabvar with the image.
3. CSS to hide it on smaller screens.

### CODE REVIEW

**Comment by pratiktamang** [comment]
The change looks like this locally. Please let me know if anything needs updating. Thanks!
https://user-images.githubusercontent.com/29284404/226300954-434e3122-e154-44a5-82dd-d4da7979b266.mov

**Review by adrianthedev — APPROVED** [review]
This looks great! Thank you!

**Comment by adrianthedev** [comment]
Good to merge @lucianghinda!

**Comment by adrianthedev** [comment]
@pratiktamang please send me an email at `adrian@adrianthedev.com`.

**Pull request merged**
